#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "${BLOCK_PATH:-"$shome/work"}/block/script/profile" ~
  source normalize  

  local nm_mode="$1"; shift
  trap "reset" EXIT
  rat --mode "$nm_mode" --cmd "$*"
}

source sub "$BASH_SOURCE" "$@"
