#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "${BLOCK_PATH:-"$shome/work"}/block/script/profile" ~
  source normalize  

  if [[ "$#" == 0 ]]; then
    set -- '*'
  fi

  exec r exec file ls -lhd "$@"
}

source sub "$BASH_SOURCE" "$@"
