#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_rat="0.0.1"
  jq -n --arg rat "$ver_rat" '{rat: $rat}'
}

version "$@"
